project_name: ifql
builds:
- goos:
  - linux
  goarch:
  - amd64
  main: ./cmd/ifqld/main.go
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: ifqld
dockers:
  -
    goos: linux
    goarch: amd64
    binary: ifqld
    image: quay.io/influxdb/ifqld
    dockerfile: Dockerfile
    latest: true
    extra_files:
    - LICENSE
    - README.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
