project_name: ifql
builds:
- goos:
  - linux
  env:
    - CGO_ENABLED=0
  goarch:
  - amd64
  flags: -installsuffix cgo
  main: ./cmd/ifqld/main.go
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: ifqld
