required = ["github.com/mna/pigeon", "github.com/goreleaser/goreleaser"]

[[constraint]]
  branch = "master"
  name = "github.com/google/go-cmp"

[[override]]
  branch = "master"
  name = "github.com/mna/pigeon"
